### PR TITLE
longer RooFit binned tests and unbinned tests

### PR DESCRIPTION
**Pull request by vincecr0ft**
The changes from the wreckage of the last few months commits have been salvaged and pieced bit by bit back into the main RooFit rootbench.

A second code splits the RooFit tests into Binned and UnBinned cases. (this reflects the differences LHCb/Babar style problems based on custom PDFs built in standalone RooFit (analytical form is known) to the ATLAS/CMS style (where the form of the PDF is estimated using a morphing scheme within HistFactory). The UnBinned code was written independently of recent updates to the code and therefore may need some optimisation (removing the profile timers etc). 

The binned test scales in both #channels and #bins each with 1-3 CPUs assigned to handle the components of the evaluation. Hesse requires that Migrad is run first and Minos that Hesse runs. A `snapshot` taken before the first minimisation is applied to reset the parameter values before the timed minimisation. As such minos, by definition, will take longer to run then Hesse and Hesse longer than Migrad as the execution of each is included however only the final minimisation is timed.

### CODE REVIEW

**Comment by vincecr0ft** [comment]
locally I run into this error:
```libc++abi.dylib: terminating with uncaught exception of type RooFit::BidirMMapPipe_impl::BidirMMapPipeException: pipe: Too many open files
Abort trap: 6```
Towards the end of the operations. This has already been mitigated by restricting profiles to a fixed number of iterations. However when including both #Channel and #Bin scaling tests the problem returns. (right at the end)

**Comment by vincecr0ft** [comment]
With respect to the comment above. I don't remember this being an issue when each workspace was called individually (instead of now where everything is just called "workspace.root"). I also know that RooFit has trouble letting go of objects (in python sometimes we have to explicitly 'disown' workspace objects created by RooFit in order to export code)

**Comment by oshadura** [comment]
@vincecr0ft, thank you so much! Great job! tests are a bit long (RT), so I would like to add them to separate "long RT benchmark group" maybe..

**Comment by oshadura** [comment]
@vincecr0ft can I ask you rebase please? :)

**Comment by oshadura** [comment]
Closing, was merged already in a different PR

**Pull request closed without merging**
