### PR TITLE
Add benchmark for some PRNGs

### PR DESCRIPTION
**Pull request by hahnjo**

### CODE REVIEW

**Review by eguiraud — APPROVED** [review]
looks good!

**Comment by hahnjo** [comment]
So the build is failing because it's using ROOT from cvmfs which was last updated in June? Any ideas how to get a more recent version? Or do we wait until current `master` is released as 6.24?

**Comment by oshadura** [comment]
@hahnjo because of changes on SFT Jenkins, root I was using here is not released anymore in CVMFS. I will move as soon as possible to use conda nighlties builds (maybe end of week?), never had a time for this....

**Comment by oshadura** [comment]
@hahnjo if you will rebase on master, GH Actions with root-nightlies from conda  will be retrigered :+1:

**Comment by hahnjo** [comment]
@oshadura still fails:
```
[ 45%] Building CXX object root/math/mathcore/CMakeFiles/TRandomBenchmarks.dir/TRandomBenchmarks.cxx.o
In file included from /home/runner/work/rootbench/rootbench/root/math/mathcore/TRandomBenchmarks.cxx:1:0:
/home/runner/work/rootbench/rootbench/root/math/mathcore/TRandomBenchmarks.cxx:21:29: error: 'TRandomRanluxpp' was not declared in this scope
 BENCHMARK_TEMPLATE(BM_Rndm, TRandomRanluxpp);
```

On the other hand, once we get a build of current `master` we first need to merge #204.

**Comment by oshadura** [comment]
@eguiraud so conda builds are not nightly?

I think I lost a bit in the calendar and didn't notice that it is November and not December builds:
```
      ~/CERN_/rootbench/builds     lilit-flamegraph *7 ?1 ▓▒░ root --version                       ░▒▓ INT ✘  root-nightly    09:11:01   
ROOT Version: 6.23/01
Built for linuxx8664gcc on Nov 05 2020, 02:11:00
From heads/master@v6-23-01-RF-binSampling-64-g4e4e1d00d9
      ~/CERN_/rootbench/builds     lilit-flamegraph *7 ?1 ▓▒░ 
```

**Comment by oshadura** [comment]
Other question, why the tag (?) is so strange: `v6-23-01-RF-binSampling-64-g4e4e1d00d9`?

**Comment by eguiraud** [comment]
they are nightly, but [currently there is an issue with LLVM](https://lcgapp-services.cern.ch/root-jenkins/view/conda/job/conda-nightlies/242/console) so they are not getting updated.

**Comment by hageboeck** [comment]
> Other question, why the tag (?) is so strange: `v6-23-01-RF-binSampling-64-g4e4e1d00d9`?

The tag is for ATLAS people. We agreed with Axel that instead of giving them an extra 6-23 dev release, which would have created extra work for Axel, they just get a tag, and do the building themselves.
Now, why some 64 and hash gets attached - no idea.

**Comment by hahnjo** [comment]
> > Other question, why the tag (?) is so strange: `v6-23-01-RF-binSampling-64-g4e4e1d00d9`?
> 
> The tag is for ATLAS people. We agreed with Axel that instead of giving them an extra 6-23 dev release, which would have created extra work for Axel, they just get a tag, and do the building themselves.
> Now, why some 64 and hash gets attached - no idea.

The format looks like `git-describe`. If that tag for ATLAS is the latest, it will be picked up by `git describe` until we have a more recent tag.

**Comment by hahnjo** [comment]
```
The following tests FAILED:
	 17 - rootbench-RDFBenchmarks (SEGFAULT)
```

I'm pretty sure that's not me...

**Comment by eguiraud** [comment]
mmh no that's definitely not you, I'll take a look

**Comment by eguiraud** [comment]
I think I found the issue, I hope https://github.com/root-project/rootbench/pull/205 mitigates/resolves it.

**Comment by hahnjo** [comment]
@oshadura same question about Travis here. Should we just deactivate the status if it's not used anymore?

**Comment by oshadura** [comment]
I tried to remove it: there is nothing in build files as well in settings, but it is still there... @eguiraud  can you help me check what I am missing please?

**Comment by hahnjo** [comment]
> I tried to remove it: there is nothing in build files as well in settings, but it is still there... @eguiraud can you help me check what I am missing please?

There's still https://github.com/root-project/rootbench/blob/master/.travis.yml, maybe we just need to remove that? Let me give that a try...

**Comment by eguiraud** [comment]
You want to deactivate travis? Removing .travis.yml should do the trick.

**Pull request merged**
