### PR TITLE
[CI] CleanupTravis files and add GH Actions

### PR DESCRIPTION
**Pull request by oshadura**

### CODE REVIEW

**Comment by oshadura** [comment]
@eguiraud I want to remove Travis, and change to GH Actions. Looks like ``` conda install -y -c https://root.cern/download/conda-nightly/latest -c conda-forge root-nightly``` is not enough....
```
      ~/CERN_/rootbench     cleanup-travis *3 !1 ?1 ▓▒░ root --version                                 ░▒▓ ✔  8s    base    15:20:17   
ERROR in cling::CIFactory::createCI(): cannot extract standard library include paths!
Invoking:
  LC_ALL=C x86_64-conda-linux-gnu-c++  -O3 -DNDEBUG -xc++ -E -v /dev/null 2>&1 | sed -n -e '/^.include/,${' -e '/^ \/.*++/p' -e '}'
Results was:
With exit code 0
ROOT Version: 6.23/01
Built for linuxx8664gcc on Nov 05 2020, 02:11:00
From heads/master@v6-23-01-RF-binSampling-64-g4e4e1d00d9
```

**Comment by oshadura** [comment]
I see @chrisburr suggested in iris-hep channel to use:
`conda create --name something root` followed by `conda activate something `,  but I can't find working combination, can you help me please?

**Comment by eguiraud** [comment]
Just tried, this works on my laptop:

```
$ conda create -n root-nightly -y -c https://root.cern/download/conda-nightly/latest -c conda-forge root-nightly 
$ conda activate root-nightly
```

**Comment by oshadura** [comment]
Works, we need to update the root web page then!
```
      ~/CERN_/rootbench     cleanup-travis *3 !1 ?1 ▓▒░ root --version                                 ░▒▓ ✔  root-nightly    15:54:56   
ROOT Version: 6.23/01
Built for linuxx8664gcc on Nov 05 2020, 02:11:00
From heads/master@v6-23-01-RF-binSampling-64-g4e4e1d00d9
```

**Comment by eguiraud** [comment]
what's different at https://root.cern/install/nightlies ?

**Comment by oshadura** [comment]
I hope I am not getting crazy, I found it somewhere and now I can't find anymore :+1:

**Comment by oshadura** [comment]
I can't check GH Actions here somehow, it suppose to work but maybe it is conflicting with activated Travis. Merging and I will fix it already in master...

**Pull request merged**
