### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by eguiraud**
This PR should fix all the warnings that we see in the nightly builds.

### CODE REVIEW

**Review by oshadura — APPROVED** [review]
LGTM! Thanks a lot!

**Comment by oshadura** [comment]
Argh, I don't understand what is happening with CI.....

**Comment by eguiraud** [comment]
Let's start by getting rid of all those roofit warnings, I'll ask on mattermost

**Comment by oshadura** [comment]
ah! maybe it is a problem, in raw logs, I just see mostly this warning is printed...

**Comment by eguiraud** [comment]
The build is red because the "run benchmarks" step exits with status code 137. A quick search indicates that might be an out-of-memory error in a docker container or similar, so the large log size might actually be the problem.

**Comment by eguiraud** [comment]
Merging this, and let's check the CI once https://github.com/root-project/root/pull/8030 is merged in ROOT: it should fix the roofit warnings

**Pull request merged**
