### PR TITLE
[TMVA] Exclude TMVA cross-validation benchmark if TMVA not enabled

### PR DESCRIPTION
**Pull request by stwunsch**
Currently breaks with `-Dtmva=OFF`!

### CODE REVIEW

**Comment by oshadura** [comment]
Nice catch!

**Comment by oshadura** [comment]
The PR is green (there is broken a coverage part, which I will fix after)

**Comment by stwunsch** [comment]
Rebased!

**Comment by oshadura** [comment]
Thanx!!! Merging!

**Pull request merged**
