### PR TITLE
[clad] Rename GradientStorage to CladStorage

### PR DESCRIPTION
**Pull request by sudo-panda**

### CODE REVIEW

**Review by oshadura — COMMENTED** [review]
Thanks for quick fix! Are you planning to add benchmarks in empty  TFormulaHessianBenchmarks.cxx file later?

**Comment by sudo-panda** [comment]
> Thanks for quick fix! Are you planning to add benchmarks in empty TFormulaHessianBenchmarks.cxx file later?

Sorry about that it wasn't supposed to be a part of this PR.

Unfortunately I am not near my PC so it will take me about 1/2 an hour to get back and only then I will be able to amend it.

**Comment by oshadura** [comment]
To retest after https://github.com/root-project/rootbench/pull/234 is merged

**Comment by sudo-panda** [comment]
Removed the extra file

**Review by oshadura — APPROVED** [review]
@sudo-panda thanks a lot for fixes! I will merge them and try to resolve problem with GH CI in separate PR

**Pull request merged**
