### PR TITLE
added RDFbench 

### PR DESCRIPTION
**Pull request by HLilit**

### CODE REVIEW

**Comment by oshadura** [comment]
@HLilit nice job! :) What I will start the first is that I will try to make Travis CI happy :) Example of failures: https://travis-ci.org/root-project/rootbench/jobs/542669954

About questions of Enrico:
1. Yes, it is possible. An example: https://github.com/root-project/rootbench/blob/master/root/hist/hist/CMakeLists.txt
2. Yes, we use next environment variable defining location of temporary storage https://github.com/root-project/rootbench/blob/master/include/rootbench/RBConfig.h#L14 and Enrico already used it in RDFBenchmark https://github.com/root-project/rootbench/blob/60ff8dacef1155b7135f182aa6086158be341cca/root/tree/dataframe/RDataFrameBenchmarks.cxx#L12

**Comment by HLilit** [comment]
Thanks Oksana and Enrico for your comments :) I'll try to fix the parts you mentioned !

**Comment by oshadura** [comment]
I am merging, but next time, @HLilit promise me to write better commit messages ;)

**Comment by HLilit** [comment]
yes, I will try =D

**Comment by vgvassilev** [comment]
Could you retrospectively add the updates following the coding conventions mentioned [here](https://github.com/root-project/rootbench#conventions)?
Thanks and sorry for the post-merge review.

**Comment by HLilit** [comment]
@vgvassilev Thank you for your comment. I wanted to ask if we can use the form CLASSNAMECLASSNAMEBenchmarks as we have some mixed benchmarks here.

**Comment by HLilit** [comment]
for example, RDataFrame_vs_Tree and TBranch_vs_ReaderArray

**Comment by vgvassilev** [comment]
Technically, RDataFrame_vs_Tree should be split into two: RDataFrameSomethingBenchmarks and TreeSomethingBenchmarks (which will end up in different folders). The `vs` part comes elsewhere, the actual comparison between the performance of RDataFrame and Tree should be displayed in the dashboard comparing the relevant benchmarks.

**Comment by HLilit** [comment]
Thanks a lot ! I'll modify them

**Pull request merged**
