### PR TITLE
Add compression benchmarks for LHCb/NanoAOD/ATLAS files

### PR DESCRIPTION
**Pull request by kamahori**
I add new compression/decompression benchmarks for files below:

- `lhcb_B2ppKK2011_md_noPIDstrip.root`
- `Run2012B_DoubleMuParked.root`
- `gg_data-zstd.root`

### CODE REVIEW

**Comment by vgvassilev** [comment]
Please consider squashing the commits or making them atomic.

**Comment by kamahori** [comment]
I squashed them into 5 commits.

**Comment by vgvassilev** [comment]
Could you find the right places of the last two commits?

**Comment by kamahori** [comment]
> Could you find the right places of the last two commits?

What do you mean? Should I squash them again?

**Comment by vgvassilev** [comment]
The cmake changes should accompany the commit which introduces the benchmark. 
When you add the first benchmark it should also touch the relevant cmake file. I think the cmake commit should be split into two and each part squashed into the relevant commit.  The typo commit should go in the commit it intends to fix if it was part of this PR, otherwise it should have more informative commit message.

**Comment by kamahori** [comment]
Thank you. I split last 2 commits and squashed them as 3 commits.

**Comment by vgvassilev** [comment]
Thanks!

**Comment by kamahori** [comment]
Why does Travis have an error?

**Pull request merged**
