### PR TITLE
[DF] Run df10[3,4] benchmarks also with ROOT::RDF::RunGraphs

### PR DESCRIPTION
**Pull request by stwunsch**

### CODE REVIEW

**Comment by eguiraud** [comment]
Cool, how are the runtimes before/after these changes?

**Comment by stwunsch** [comment]
I don't see much changes in my dev system. but this one has only 2(+2) cores ...

**Comment by stwunsch** [comment]
Is it good to go? We'll see the runtime tomorrow morning ;)

**Comment by eguiraud** [comment]
Can you check on the rootbench machine please? If we expect an improvement and we don't see it, there is something to be understood, if we don't expect an improvement in this benchmark, then we should make another benchmark to exercise RunGraphs explicitly.

**Comment by stwunsch** [comment]
```
-------------------------------------------------------------------------------------------- benchmark: 3 tests --------------------------------------------------------------------------------------------
1095: Name (time in s)                                  Min                Max               Mean            StdDev             Median               IQR            Outliers     OPS            Rounds  Iterations
1095: ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1095: test_df103_NanoAODHiggsAnalysis_rungraphs     10.3923 (1.0)      10.3923 (1.0)      10.3923 (1.0)      0.0000 (1.0)      10.3923 (1.0)      0.0000 (1.0)           0;0  0.0962 (1.0)           1           1
1095: test_df103_NanoAODHiggsAnalysis_imt           14.1225 (1.36)     14.1225 (1.36)     14.1225 (1.36)     0.0000 (1.0)      14.1225 (1.36)     0.0000 (1.0)           0;0  0.0708 (0.74)          1           1
1095: test_df103_NanoAODHiggsAnalysis_noimt         20.3751 (1.96)     20.3751 (1.96)     20.3751 (1.96)     0.0000 (1.0)      20.3751 (1.96)     0.0000 (1.0)           0;0  0.0491 (0.51)          1           1
1095: ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

```

```
------------------------------------------------------------------------------------------- benchmark: 3 tests ------------------------------------------------------------------------------------------
1097: Name (time in s)                               Min                Max               Mean            StdDev             Median               IQR            Outliers     OPS            Rounds  Iterations
1097: ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1097: test_df104_HiggsToTwoPhotons_rungraphs     14.6050 (1.0)      14.6050 (1.0)      14.6050 (1.0)      0.0000 (1.0)      14.6050 (1.0)      0.0000 (1.0)           0;0  0.0685 (1.0)           1           1
1097: test_df104_HiggsToTwoPhotons_imt           15.0534 (1.03)     15.0534 (1.03)     15.0534 (1.03)     0.0000 (1.0)      15.0534 (1.03)     0.0000 (1.0)           0;0  0.0664 (0.97)          1           1
1097: test_df104_HiggsToTwoPhotons_noimt         59.0830 (4.05)     59.0830 (4.05)     59.0830 (4.05)     0.0000 (1.0)      59.0830 (4.05)     0.0000 (1.0)           0;0  0.0169 (0.25)          1           1
1097: ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

```
1093: -------------------------------------------------------------------------------------------
1093: Benchmark                                                 Time             CPU   Iterations
1093: -------------------------------------------------------------------------------------------
1093: df103_NanoAODHiggsAnalysis_noimt/repeats:1       16904675905 ns   16858546018 ns            1
1093: df103_NanoAODHiggsAnalysis_imt/8/repeats:1       8123889470 ns   8119034604 ns            1
1093: df103_NanoAODHiggsAnalysis_rungraphs/8/repeats:1 7904714307 ns   7895863978 ns            1

```

**Comment by stwunsch** [comment]
hum strange behaviour, no?

**Comment by eguiraud** [comment]
looks reasonable to me, what's strange?

**Comment by stwunsch** [comment]
`df103*.py` scales nicely with `RunGraphs` (it's little data!) but `df103*.C` does not :thinking: The C++ version is the last one.

**Comment by stwunsch** [comment]
But I agree, it's not totally weird.

**Review by eguiraud — APPROVED** [review]

**Pull request merged**
