### PR TITLE
Remove CI definition for Travis

### PR DESCRIPTION
**Pull request by hahnjo**

### CODE REVIEW

**Comment by oshadura** [comment]
I was sure I removed it...

**Comment by hahnjo** [comment]
@oshadura @eguiraud it's still trying to run on Travis :-(

**Comment by eguiraud** [comment]
...now removing rootbench from travis at travis-ci.org...

**Comment by eguiraud** [comment]
image

**Comment by oshadura** [comment]
Thanks! I am a bit out of mind last weeks...

**Comment by hahnjo** [comment]
Bildschirmfoto vom 2020-12-15 10-55-54

grafik

**Comment by eguiraud** [comment]
image

image

image

**Pull request merged**
