### PR TITLE
[RDF] Make wmass benchmark running with py3

### PR DESCRIPTION
**Pull request by stwunsch**

### CODE REVIEW

**Comment by eguiraud** [comment]
Thanks! This makes it _only_ work with py3. Can you please add a `from __future__ import print_function` at the top of these files?

**Comment by stwunsch** [comment]
I guess not, right? You can also use `print(whatever)` in python2!

**Comment by eguiraud** [comment]
> You can also use print(whatever) in python2

not really?

**Comment by eguiraud** [comment]
Oh damn, yes you can -- since when? xD

**Comment by eguiraud** [comment]
aaaah no, `print(foo,bar)` is evaluated as `print (foo, bar)` in python2. There are case in which that fails.

**Pull request merged**
